
["Boss Health"]
	#Health for specified mob.
	"Gob, King of Gnomes Health" = 450.0
	#Health for specified mob.
	"Super Sniffer Health" = 2000.0
	#Health for specified mob.
	"Ultra Sniffer Health" = 10000.0
	#Health for specified mob.
	"Trial Guardian Health" = 5000.0
	#Health for specified mob.
	"Virtue Health" = 4000.0
	#Health for specified mob.
	"Enchanter Merlin Health" = 15000.0
	#Health for specified mob.
	"Sorceress Circe Health" = 15000.0
	#Health for specified mob.
	"Archmage Gundalf Health" = 20000.0
	#Health for specified mob.
	"Multiplayer Boss Health Scaling" = true

["Mob Health"]
	#Health for specified mob.
	"Duskrok Health" = 500.0
	#Health for specified mob.
	"Hellrok Health" = 500.0

[Bosses]
	#If true, Terramity bosses will despawn after you die.
	"Can Bosses Despawn" = false

["Mob Griefing"]
	#If false, Terramity mobs will (mostly) not damage terrain.
	MobGriefing = false

